import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <div className="p-4 bg-rose-100 flex justify-center border-2 border-amber-800">
            <div className='border-2 border-red-500 flex justify-between items-center w-full'>
              <div className='w-7/12 flex justify-end'>
                <a href="/" className="text-2xl font-mono text-center border-2">The Social Art Platform</a>
              </div>
              <div>
                <nav className="space-x-4 border-2">
                  <a href="/" className="text-lg">Feed</a>
                  <a href="/create" className="text-lg">Create</a>
                  <a href="/profile" className="text-lg">Profile</a>
                </nav>
              </div>
              <div className='border-2'>
                <SignedOut>
                  <SignInButton />
                </SignedOut>
                <SignedIn>
                  <UserButton />
                </SignedIn>
              </div>
            </div>
          </div>
          <main>{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
